services:
  db:
    image: postgres:16-alpine
    container_name: realico_comidas_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 10

  backend:
    image: ghcr.io/franciscotaurian/realico-comidas-backend:v0.1.0
    container_name: realico_comidas_backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PORT=8080
    depends_on:
      db:
        condition: service_healthy # espera a que la BD esté LISTA, no solo iniciada

  frontend:
    image: ghcr.io/franciscotaurian/realico-comidas-frontend:v0.1.0
    container_name: realico_comidas_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
